### ISSUE TITLE
Can't add new version of any software

### ISSUE THREAD

**Issue by jonbrown21** [grovetech/Shine-Bootstrap#2]
Software should be allowed to be uploaded to a specified directory on the web server OR to an Amazon bucket if unspecified. As of now uploading to a local directory is not working. 

<img width="446" alt="screen shot 2018-08-28 at 8 52 36 pm" src="https://user-images.githubusercontent.com/1732890/44758928-1c225b80-ab05-11e8-9f55-dfc3a73d7712.png">

**Comment by nadirhamid** [comment]
hello @jonbrown21,

can you please reference the page this issue refers to with the input you are using and what you expect in terms of the result ?

thanks

**Comment by jonbrown21** [comment]
In this area, on the /index.php page

<img width="235" alt="screen shot 2018-09-24 at 11 17 27 am" src="https://user-images.githubusercontent.com/1732890/45961070-af0ec280-bfeb-11e8-9756-b56b70eb510a.png">

The form sets to post and then to insert a new app name into the database. The post code works, *(isset) but the insert database object is not working. We need to ensure that the database objects are optimized to work with my server stack as outlined in the previous issue's notes.

**Comment by jonbrown21** [comment]
@nadirhamid Ok closing out this issue, I figured out why the DB was not writing. Found actual bugs though once I got the PHP ERROR code to work will open individual tickets.
