### ISSUE TITLE
Can not change or modify DB information

### ISSUE THREAD

**Issue by jonbrown21** [grovetech/Shine-Bootstrap#7]
I cant update any of the information in the database for any of these views

/version-edit.php?id=91

/version-new.php?id=2

/application.php?id=2

when I save the information the screen flickers and the old database information remains.

**Comment by nadirhamid** [comment]
hello @jonbrown21,

can you please send an example of using version-new.php page. I am able to see it add new records. are you uploading files. Noticed there is no warning when files are not adding. please provide an example of your input.

thanks

**Comment by nadirhamid** [comment]
@jonbrown21 here is an example
![see-1](https://user-images.githubusercontent.com/7277417/45958437-f8204000-c006-11e8-9e7e-18bcd4732dbf.png)
![see-2](https://user-images.githubusercontent.com/7277417/45958438-f8204000-c006-11e8-9d00-2f5e963d88f4.png)

**Comment by jonbrown21** [comment]
Just to make sure we are comparing apples to apples. Make sure your environment includes the recent commits I made which fix the UI element components. Here also is my server stack info. 

PHP: 
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

Apache:
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2018-04-25T11:38:24

MYSQL:
mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper

When I try to add a new version regardless of how I do so, meaning if I do or don't upload a file it does nothing regardless. Screen loads, nothing shows up in the database in PHPMYADMIN

![ezgif-1-684cee50e4](https://user-images.githubusercontent.com/1732890/45960875-314ab700-bfeb-11e8-8d1c-055518935295.gif)

**Comment by jonbrown21** [comment]
We need to ensure that the file upload system works also. Here's how it should work. 

1. If a bucket is configured for S3 for a specific app, when uploading it should upload and digitally sign a copy of the uploaded .zip file there

2. If no bucket is configured, the path to the uploads folder can be defined in the new version screen.  When uploading it should upload and digitally sign a copy of that uploaded .zip file there

**Comment by nadirhamid** [comment]
hello @jonbrown21,

my info:
PHP
PHP 7.1.19 (cli) (built: Jun 21 2018 07:18:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

apache
NONE - running on PHP dev server
"php -S"

mysql:
mysql  Ver 14.14 Distrib 5.6.40, for Linux (x86_64) using  EditLine wrapper

did you change the database settings in: includes/class.config.php ?

**Comment by jonbrown21** [comment]
Yes I did. I will send you credentials as well as a copy of the config file so you can see.

**Comment by jonbrown21** [comment]
I sent you the config dump and creds via DM on GURU

**Comment by nadirhamid** [comment]
hello @jonbrown21,

can you also enable PHP error reporting and set "display_errors" to On?

**Comment by jonbrown21** [comment]
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

has been added to the master.inc.php file

and display_errors = on is enabled at the PHP INI level.

**Comment by nadirhamid** [comment]
@jonbrown21 

did you get any messages or is it still just not adding the records ?

**Comment by jonbrown21** [comment]
Just not adding records at all. No messages

**Comment by jonbrown21** [comment]
@nadirhamid Ok closing out this issue, I figured out why the DB was not writing. Found actual bugs though once I got the PHP ERROR code to work will open individual tickets.
