### ISSUE TITLE
Order NOTES field not saving data

### ISSUE THREAD

**Issue by jonbrown21** [grovetech/Shine-Bootstrap#8]
/order.php?id=4

Steps to reproduce. 
change ID to reflect the ORDER number and then try to save a note. No error just no note saved, or no note PHP echo'd into the textarea.

**Comment by jonbrown21** [comment]
Order notes still do not update after merge.

**Comment by nadirhamid** [comment]
hello @jonbrown21,

about this: i tested on my end and i am able to see it working. can you show the output of the query that is creating/updating the record for the notes ? also the output for it when it is called with mysqli ?

thanks

**Comment by jonbrown21** [comment]
hello @nadirhamid 

The post is empty no matter what value is submitted on the notes update form, on the edit order screen. This is likely the issue. In the console there is no output other than NULL. It never makes it to the MYSQLi part because it never gets triggered by PHP isset
